version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/kali2/Documentos/dependency-check:/opt/dependency-check
    networks:
      - devsecops

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9001:9000"
    networks:
      - devsecops

networks:
  devsecops:

volumes:
  jenkins_home:
