services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-devsecops
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPTS=-Djava.io.tmpdir=/var/jenkins_home/jenkins_tmp
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/jenkins_tmp:/var/jenkins_tmp
      - /home/kali2/Documentos/dependency-check:/opt/dependency-check
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    group_add:
      - 136
    user: root
    networks:
      - devsecops

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_JAVA_OPTS=-Xmx1024m -Xms512m
    volumes:
      - /var/jenkins_home/sonarqube_data:/opt/sonarqube/data
      - /var/jenkins_home/sonarqube_logs:/opt/sonarqube/logs
      - /var/jenkins_home/sonarqube_extensions:/opt/sonarqube/extensions
      - /var/jenkins_home/sonarqube_temp:/opt/sonarqube/temp
    networks:
      - devsecops
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g

networks:
  devsecops:
