version: 1.0
jobs:
  - name: Basico Active Scan
    type: active-scan
    parameters:
      url: http://host.docker.internal:5000
      recurse: true
      method: GET
      policy: Default Policy
reports:
  - name: html-report
    template: traditional-html-report
    file: zap-report.html
