version: 1.0

environments:
  - name: default-env
    host: "http://host.docker.internal"
    port: 5000
    context:
      name: Default Context
      include:
        - url: "http://host.docker.internal:5000.*"

jobs:
  - name: Spider Job
    type: spider
    parameters:
      context: Default Context
  - name: Active Scan Job
    type: activeScan
    parameters:
      context: Default Context

reports:
  - name: HTML Report
    template: traditional-html-report
    file: zap-report.html
