version: "1.0"

environments:
  - name: default-env
    host: "http://localhost"
    port: 5000

contexts:
  - name: Default Context
    include:
      - url: "http://localhost:5000.*"

jobs:
  - name: Spider Job
    type: spider
    context: Default Context
    parameters: {}

  - name: Active Scan Job
    type: activeScan
    context: Default Context
    parameters: {}

reports:
  - name: HTML Report
    template: traditional-html-report
    file: zap-report.html
