version: 1.0
environments:
  - name: default-env
    host: "http://host.docker.internal:5000"
    port: 80
    context:
      name: Default Context
      include:
        - url: "http://host.docker.internal:5000.*"
jobs:
  - name: Scan Job
    type: spider
    parameters:
      context: Default Context
      maxDepth: 5
  - name: Active Scan Job
    type: activeScan
    parameters:
      context: Default Context
      policy: Default Policy

reports:
  - name: HTML Report
    template: traditional-html-report
    file: zap-report.html
